#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2501-19-g42c18187"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2501
#define NETGEN_VERSION_TWEAK 19
#define NETGEN_VERSION_HASH "g42c18187"
#endif // NETGEN_VERSION_HPP_INCLUDED
