# Generated by Django 5.1.3 on 2024-11-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_alliance", "0010_alliance_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alliance",
            name="code_alliance",
            field=models.SlugField(
                blank=True,
                help_text="Code Alliance",
                max_length=150,
                null=True,
                verbose_name="Code",
            ),
        ),
    ]
