"""
TODO: remove before production
AZURE_OPENAI_ENDPOINT=https://aws.openai.azure.com/
AZURE_OPENAI_API_KEY=9apB9EtnpbOJYqPS0vzEbr8T976woI5FYLtnN2HdnTRkQymT5lZNJQQJ99AKACYeBjFXJ3w3AAABACOGFyYH
AZURE_OPENAI_API_VERSION=2024-08-01-preview
AZURE_OPENAI_DEPLOYMENT_NAME=gpt-4o
"""