ACTION_ENDPOINT = "/actions/"
CREATE_ACTION_ENDPOINT = f"{ACTION_ENDPOINT}create"
SINGLE_ACTION_ENDPOINT = ACTION_ENDPOINT + "{id}"
ACTION_DATA_ENDPOINT = f"{SINGLE_ACTION_ENDPOINT}/data"
GET_PROMPT_ENDPOINT = f"{SINGLE_ACTION_ENDPOINT}/gateway_payload"
PLAYGROUND_PROMPT_ENDPOINT = f"{ACTION_ENDPOINT}playground"
DEPLOY_ACTION_ENDPOINT = f"{SINGLE_ACTION_ENDPOINT}/deploy"
DISABLE_ACTION_ENDPOINT = f"{SINGLE_ACTION_ENDPOINT}/disable"
VERSIONS_ACTION_ENDPOINT = f"{SINGLE_ACTION_ENDPOINT}/versions"
ACTION_SKILL_ENDPOINT = f"{SINGLE_ACTION_ENDPOINT}/skills"
ACTION_CONTEXT_ENDPOINT = f"{SINGLE_ACTION_ENDPOINT}/context"

DEFAULT_ACTIONS_PAGE_SIZE = 50
