# -*- coding: utf-8 -*-

"""
accountandtransactionapispecification

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatementBenefitTypeEnum(object):

    """Implementation of the 'StatementBenefitType' enum.

    Benefit type, in a coded form.

    Attributes:
        CASHBACK: The enum member of type str.
        INSURANCE: The enum member of type str.
        TRAVELDISCOUNT: The enum member of type str.
        TRAVELINSURANCE: The enum member of type str.

    """
    CASHBACK = 'Cashback'

    INSURANCE = 'Insurance'

    TRAVELDISCOUNT = 'TravelDiscount'

    TRAVELINSURANCE = 'TravelInsurance'

