# coding: utf-8

"""
    Hightop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_actions_agent_withdraw_post_request import ApiActionsAgentWithdrawPostRequest

class TestApiActionsAgentWithdrawPostRequest(unittest.TestCase):
    """ApiActionsAgentWithdrawPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiActionsAgentWithdrawPostRequest:
        """Test ApiActionsAgentWithdrawPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiActionsAgentWithdrawPostRequest`
        """
        model = ApiActionsAgentWithdrawPostRequest()
        if include_optional:
            return ApiActionsAgentWithdrawPostRequest(
                agentic_wallet = None,
                lego_id = None,
                asset = None,
                vault_token = None,
                amount = None,
                message = openapi_client.models._api_actions_agent_batch_post_request_message._api_actions_agent_batch_post_request_message(
                    message = '', 
                    agent_context = '', ),
                local_message_id = ''
            )
        else:
            return ApiActionsAgentWithdrawPostRequest(
                agentic_wallet = None,
                lego_id = None,
                asset = None,
                vault_token = None,
                message = openapi_client.models._api_actions_agent_batch_post_request_message._api_actions_agent_batch_post_request_message(
                    message = '', 
                    agent_context = '', ),
        )
        """

    def testApiActionsAgentWithdrawPostRequest(self):
        """Test ApiActionsAgentWithdrawPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
