
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-19T10:55:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "68a94217b683ae97d803809b722084875b566cf4",
 "version": "2.57.1b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
