# Generated by Django 5.0.1 on 2024-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artd_product",
            "0013_rename_secondary_mini_image_category_secondary_mini_image",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryByUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="status")),
                (
                    "source",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Enter the source of the product",
                        null=True,
                        verbose_name="Source",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Enter the json data of the product",
                        null=True,
                        verbose_name="Json data",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Enter the external id of the product",
                        max_length=250,
                        null=True,
                        verbose_name="External id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the category by url",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "url",
                    models.SlugField(
                        help_text="Enter the url of the category by url",
                        max_length=250,
                        verbose_name="Url",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="Select the category",
                        to="artd_product.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category By Url",
                "verbose_name_plural": "Category By Urls",
            },
        ),
    ]
