# Generated by Django 5.1.1 on 2024-09-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artd_channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('provider', models.CharField(max_length=255)),
                ('credentials', models.JSONField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artd_channels.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
