import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_03ef3381c9(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_99fdc54397():spartaqube_cli.list()
@app.command()
def sparta_45371087ac():spartaqube_cli.sparta_45371087ac()
@app.command()
def sparta_65343e1361():print('Hello world!')
if __name__=='__main__':app()