
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-21T14:56:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "283d86a8b0ca4744f97b71cd662ddfac2bf348e9",
 "version": "2.20.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
