from .schedules import ElucidatedDiffusionModelsSchedule, VariancePreservingSchedule, VarianceExplodingSchedule


EDMSchedule = ElucidatedDiffusionModelsSchedule
VPSchedule = VariancePreservingSchedule
VESchedule = VarianceExplodingSchedule