# Generated by Django 5.0.1 on 2024-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_price_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="External ID",
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="source",
            field=models.JSONField(
                blank=True, help_text="Source", null=True, verbose_name="Source"
            ),
        ),
        migrations.AddField(
            model_name="pricelistlog",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="External ID",
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AddField(
            model_name="pricelistlog",
            name="source",
            field=models.JSONField(
                blank=True, help_text="Source", null=True, verbose_name="Source"
            ),
        ),
    ]
