# Generated by Django 5.0.1 on 2024-03-10 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artd_partner",
            "0005_alter_coworker_created_at_alter_coworker_updated_at_and_more",
        ),
        ("artd_price_list", "0002_pricelist_external_id_pricelist_source_and_more"),
        (
            "artd_product",
            "0013_rename_secondary_mini_image_category_secondary_mini_image",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelist",
            name="partner",
            field=models.ForeignKey(
                help_text="Partner",
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_partner.partner",
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="product",
            field=models.ForeignKey(
                help_text="Product",
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_product.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="pricelistlog",
            name="partner",
            field=models.ForeignKey(
                help_text="Partner",
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_partner.partner",
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="pricelistlog",
            name="product",
            field=models.ForeignKey(
                help_text="Product",
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_product.product",
                verbose_name="Product",
            ),
        ),
    ]
