import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_40754eb8a5(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_a3ef60faa3():spartaqube_cli.list()
@app.command()
def sparta_decc6c139d():spartaqube_cli.sparta_decc6c139d()
@app.command()
def sparta_8d5e2c4e55():print('Hello world!')
if __name__=='__main__':app()