from .samplers import ElucidatedDiffusionModelsEulerSampler, ElucidatedDiffusionModelsHeunSampler


EDMEulerSampler = ElucidatedDiffusionModelsEulerSampler
EDMHeunSampler = ElucidatedDiffusionModelsHeunSampler