from .samplers import ElucidatedDiffusionModelsEulerSampler, ElucidatedDiffusionModelsHeunSampler


class EDMEulerSampler(ElucidatedDiffusionModelsEulerSampler): ...
class EDMHeunSampler(ElucidatedDiffusionModelsHeunSampler): ...