from tech_tools.detective_functions import local_devices, semi_local_devices
from tech_tools.utilities import tcp_ip_port_scanner
from tech_tools.wireshark import wireshark_private_ips, wireshark_mac_addresses

from tech_tools.scripts.tech_tools_simple_script import quick_start
