# Generated by Django 5.0.1 on 2024-02-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_product", "0003_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupedproduct",
            name="variations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Enter the variations of the grouped product",
                null=True,
                verbose_name="Variations",
            ),
        ),
    ]
