# Generated by Django 5.1.7 on 2025-03-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0005_rename_location_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="The code used to identify the country.",
                        max_length=2,
                        verbose_name="code",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="The name of the country.", verbose_name="name"
                    ),
                ),
                (
                    "place",
                    models.TextField(
                        help_text="The hierarchical name of the country.",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="The country for the location.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="checklists.country",
                verbose_name="country",
            ),
        ),
    ]
