# Generated by Django 5.1.7 on 2025-03-20 16:50

from django.db import migrations


def set_district(apps, schema_editor):
    Location = apps.get_model("checklists", "Location")
    District = apps.get_model("checklists", "District")
    for location in Location.objects.all():
        district, created = District.objects.get_or_create(
            code=location.county_code,
            defaults={
                "name": location.county,
                "place": "%s, %s, %s" % (location.county, location.region.name, location.country.name),
            }
        )
        location.district = district
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0012_add_district"),
    ]

    operations = [
        migrations.RunPython(set_district),
    ]
