# Generated by Django 5.1.7 on 2025-03-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0014_remove_location_county_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="The code used to identify the area.",
                        max_length=6,
                        verbose_name="code",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="The name of the area.", verbose_name="name"
                    ),
                ),
                (
                    "place",
                    models.TextField(
                        help_text="The hierarchical name of the area.",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "area",
                "verbose_name_plural": "areas",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="The area for the location.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="checklists.area",
                verbose_name="area",
            ),
        ),
    ]
