# coding: utf-8

"""
    Forgejo API

    This documentation describes the Forgejo API.

    The version of the OpenAPI document: 10.0.0-93-60eedb9+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_forgejo.models.change_files_options import ChangeFilesOptions

class TestChangeFilesOptions(unittest.TestCase):
    """ChangeFilesOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeFilesOptions:
        """Test ChangeFilesOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangeFilesOptions`
        """
        model = ChangeFilesOptions()
        if include_optional:
            return ChangeFilesOptions(
                author = clientapi_forgejo.models.identity.Identity(
                    email = '', 
                    name = '', ),
                branch = '',
                committer = clientapi_forgejo.models.identity.Identity(
                    email = '', 
                    name = '', ),
                dates = clientapi_forgejo.models.commit_date_options.CommitDateOptions(
                    author = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    committer = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                files = [
                    clientapi_forgejo.models.change_file_operation.ChangeFileOperation(
                        content = '', 
                        from_path = '', 
                        operation = 'create', 
                        path = '', 
                        sha = '', )
                    ],
                message = '',
                new_branch = '',
                signoff = True
            )
        else:
            return ChangeFilesOptions(
                files = [
                    clientapi_forgejo.models.change_file_operation.ChangeFileOperation(
                        content = '', 
                        from_path = '', 
                        operation = 'create', 
                        path = '', 
                        sha = '', )
                    ],
        )
        """

    def testChangeFilesOptions(self):
        """Test ChangeFilesOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
