# coding: utf-8

"""
    Forgejo API

    This documentation describes the Forgejo API.

    The version of the OpenAPI document: 10.0.0-93-60eedb9+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_forgejo.models.payload_commit import PayloadCommit

class TestPayloadCommit(unittest.TestCase):
    """PayloadCommit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayloadCommit:
        """Test PayloadCommit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayloadCommit`
        """
        model = PayloadCommit()
        if include_optional:
            return PayloadCommit(
                added = [
                    ''
                    ],
                author = clientapi_forgejo.models.payload_user.PayloadUser(
                    email = '', 
                    name = '', 
                    username = '', ),
                committer = clientapi_forgejo.models.payload_user.PayloadUser(
                    email = '', 
                    name = '', 
                    username = '', ),
                id = '',
                message = '',
                modified = [
                    ''
                    ],
                removed = [
                    ''
                    ],
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                url = '',
                verification = clientapi_forgejo.models.payload_commit_verification.PayloadCommitVerification(
                    payload = '', 
                    reason = '', 
                    signature = '', 
                    signer = clientapi_forgejo.models.payload_user.PayloadUser(
                        email = '', 
                        name = '', 
                        username = '', ), 
                    verified = True, )
            )
        else:
            return PayloadCommit(
        )
        """

    def testPayloadCommit(self):
        """Test PayloadCommit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
