def create_log_message(location: str, url: str, method: str) -> str: ...

def shorten(path: str) -> str: ...

def dash_sep_strings(*args: str) -> str: ...

def create_description_for_monthly_video(monthly_video: str) -> str: ...

def video_type_response(video_path: str, video_type: str) -> dict[str, str]: ...