# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frogml_proto.qwak.administration/account/v1/jfrog_tenant_details.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9qwak/administration/account/v1/jfrog_tenant_details.proto\x12\x1eqwak.administration.account.v1\"\xe5\x01\n\x12JfrogTenantDetails\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12^\n\x1d\x64\x65\x66\x61ult_jfrog_project_details\x18\x02 \x01(\x0b\x32\x33.qwak.administration.account.v1.JfrogProjectDetailsB\x02\x18\x01\x12\\\n\x1ajfrog_tenant_configuration\x18\x03 \x01(\x0b\x32\x38.qwak.administration.account.v1.JFrogTenantConfiguration\"v\n\x18JFrogTenantConfiguration\x12Z\n\x1d\x64\x65\x66\x61ult_jfrog_project_details\x18\x01 \x01(\x0b\x32\x33.qwak.administration.account.v1.JfrogProjectDetails\"*\n\x13JfrogProjectDetails\x12\x13\n\x0bproject_key\x18\x01 \x01(\t\"t\n\x0fJfrogTenantSpec\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12N\n\x14\x64\x65\x66\x61ult_project_spec\x18\x02 \x01(\x0b\x32\x30.qwak.administration.account.v1.JfrogProjectSpec\"\'\n\x10JfrogProjectSpec\x12\x13\n\x0bproject_key\x18\x01 \x01(\tB\xb4\x01\n)com.qwak.ai.administration.api.account.v1P\x01Z\x84\x01github.com/qwak-ai/qwak-platform/services/core/java/user-management/user-management-api/pb/qwak/administration/account/v1;account_v0b\x06proto3')



_JFROGTENANTDETAILS = DESCRIPTOR.message_types_by_name['JfrogTenantDetails']
_JFROGTENANTCONFIGURATION = DESCRIPTOR.message_types_by_name['JFrogTenantConfiguration']
_JFROGPROJECTDETAILS = DESCRIPTOR.message_types_by_name['JfrogProjectDetails']
_JFROGTENANTSPEC = DESCRIPTOR.message_types_by_name['JfrogTenantSpec']
_JFROGPROJECTSPEC = DESCRIPTOR.message_types_by_name['JfrogProjectSpec']
JfrogTenantDetails = _reflection.GeneratedProtocolMessageType('JfrogTenantDetails', (_message.Message,), {
  'DESCRIPTOR' : _JFROGTENANTDETAILS,
  '__module__' : 'qwak.administration.account.v1.jfrog_tenant_details_pb2'
  # @@protoc_insertion_point(class_scope:qwak.administration.account.v1.JfrogTenantDetails)
  })
_sym_db.RegisterMessage(JfrogTenantDetails)

JFrogTenantConfiguration = _reflection.GeneratedProtocolMessageType('JFrogTenantConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _JFROGTENANTCONFIGURATION,
  '__module__' : 'qwak.administration.account.v1.jfrog_tenant_details_pb2'
  # @@protoc_insertion_point(class_scope:qwak.administration.account.v1.JFrogTenantConfiguration)
  })
_sym_db.RegisterMessage(JFrogTenantConfiguration)

JfrogProjectDetails = _reflection.GeneratedProtocolMessageType('JfrogProjectDetails', (_message.Message,), {
  'DESCRIPTOR' : _JFROGPROJECTDETAILS,
  '__module__' : 'qwak.administration.account.v1.jfrog_tenant_details_pb2'
  # @@protoc_insertion_point(class_scope:qwak.administration.account.v1.JfrogProjectDetails)
  })
_sym_db.RegisterMessage(JfrogProjectDetails)

JfrogTenantSpec = _reflection.GeneratedProtocolMessageType('JfrogTenantSpec', (_message.Message,), {
  'DESCRIPTOR' : _JFROGTENANTSPEC,
  '__module__' : 'qwak.administration.account.v1.jfrog_tenant_details_pb2'
  # @@protoc_insertion_point(class_scope:qwak.administration.account.v1.JfrogTenantSpec)
  })
_sym_db.RegisterMessage(JfrogTenantSpec)

JfrogProjectSpec = _reflection.GeneratedProtocolMessageType('JfrogProjectSpec', (_message.Message,), {
  'DESCRIPTOR' : _JFROGPROJECTSPEC,
  '__module__' : 'qwak.administration.account.v1.jfrog_tenant_details_pb2'
  # @@protoc_insertion_point(class_scope:qwak.administration.account.v1.JfrogProjectSpec)
  })
_sym_db.RegisterMessage(JfrogProjectSpec)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.qwak.ai.administration.api.account.v1P\001Z\204\001github.com/qwak-ai/qwak-platform/services/core/java/user-management/user-management-api/pb/qwak/administration/account/v1;account_v0'
  _JFROGTENANTDETAILS.fields_by_name['default_jfrog_project_details']._options = None
  _JFROGTENANTDETAILS.fields_by_name['default_jfrog_project_details']._serialized_options = b'\030\001'
  _JFROGTENANTDETAILS._serialized_start=94
  _JFROGTENANTDETAILS._serialized_end=323
  _JFROGTENANTCONFIGURATION._serialized_start=325
  _JFROGTENANTCONFIGURATION._serialized_end=443
  _JFROGPROJECTDETAILS._serialized_start=445
  _JFROGPROJECTDETAILS._serialized_end=487
  _JFROGTENANTSPEC._serialized_start=489
  _JFROGTENANTSPEC._serialized_end=605
  _JFROGPROJECTSPEC._serialized_start=607
  _JFROGPROJECTSPEC._serialized_end=646
# @@protoc_insertion_point(module_scope)
