# coding: utf-8

"""
    Hightop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wrap_eth_payload import WrapEthPayload

class TestWrapEthPayload(unittest.TestCase):
    """WrapEthPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WrapEthPayload:
        """Test WrapEthPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WrapEthPayload`
        """
        model = WrapEthPayload()
        if include_optional:
            return WrapEthPayload(
                agentic_wallet = None,
                amount = None,
                deposit_lego_id = None,
                deposit_vault = None,
                message = openapi_client.models._api_actions_agent_batch_post_request_message._api_actions_agent_batch_post_request_message(
                    message = '', 
                    agent_context = '', ),
                local_message_id = ''
            )
        else:
            return WrapEthPayload(
                agentic_wallet = None,
                message = openapi_client.models._api_actions_agent_batch_post_request_message._api_actions_agent_batch_post_request_message(
                    message = '', 
                    agent_context = '', ),
        )
        """

    def testWrapEthPayload(self):
        """Test WrapEthPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
