# coding: utf-8

"""
    Hightop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_user_settings_yield_optimizer_post_request import ApiUserSettingsYieldOptimizerPostRequest

class TestApiUserSettingsYieldOptimizerPostRequest(unittest.TestCase):
    """ApiUserSettingsYieldOptimizerPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiUserSettingsYieldOptimizerPostRequest:
        """Test ApiUserSettingsYieldOptimizerPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiUserSettingsYieldOptimizerPostRequest`
        """
        model = ApiUserSettingsYieldOptimizerPostRequest()
        if include_optional:
            return ApiUserSettingsYieldOptimizerPostRequest(
                enabled = True,
                wallet = None
            )
        else:
            return ApiUserSettingsYieldOptimizerPostRequest(
                enabled = True,
                wallet = None,
        )
        """

    def testApiUserSettingsYieldOptimizerPostRequest(self):
        """Test ApiUserSettingsYieldOptimizerPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
