# coding: utf-8

"""
    Hightop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_user_get_get200_response_wallets_inner import ApiUserGetGet200ResponseWalletsInner

class TestApiUserGetGet200ResponseWalletsInner(unittest.TestCase):
    """ApiUserGetGet200ResponseWalletsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiUserGetGet200ResponseWalletsInner:
        """Test ApiUserGetGet200ResponseWalletsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiUserGetGet200ResponseWalletsInner`
        """
        model = ApiUserGetGet200ResponseWalletsInner()
        if include_optional:
            return ApiUserGetGet200ResponseWalletsInner(
                wallet_address = None,
                owner_wallet_address = None,
                smart_account_address = None,
                yield_optimizer_enabled = True
            )
        else:
            return ApiUserGetGet200ResponseWalletsInner(
                wallet_address = None,
                owner_wallet_address = None,
                smart_account_address = None,
        )
        """

    def testApiUserGetGet200ResponseWalletsInner(self):
        """Test ApiUserGetGet200ResponseWalletsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
