# Generated by Django 5.1.7 on 2025-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0003_set_observation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="date",
            field=models.DateField(
                db_index=True,
                help_text="The date the observation was made.",
                verbose_name="date",
            ),
        ),
    ]
