# Generated by Django 5.1.7 on 2025-03-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0015_add_area"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="area",
            new_name="coverage",
        ),
    ]
