# coding: utf-8

"""
    Hightop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.message_user_send_context import MessageUserSendContext
from typing import Optional, Set
from typing_extensions import Self

class MessageUserSend(BaseModel):
    """
    MessageUserSend
    """ # noqa: E501
    agentic_wallet: Optional[Any] = Field(description="Ethereum address", alias="agenticWallet")
    message: StrictStr
    agent_contract: Optional[Any] = Field(description="Ethereum address", alias="agentContract")
    local_id: Optional[StrictStr] = Field(default=None, alias="localId")
    context: Optional[MessageUserSendContext] = None
    __properties: ClassVar[List[str]] = ["agenticWallet", "message", "agentContract", "localId", "context"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageUserSend from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['context'] = self.context.to_dict()
        # set to None if agentic_wallet (nullable) is None
        # and model_fields_set contains the field
        if self.agentic_wallet is None and "agentic_wallet" in self.model_fields_set:
            _dict['agenticWallet'] = None

        # set to None if agent_contract (nullable) is None
        # and model_fields_set contains the field
        if self.agent_contract is None and "agent_contract" in self.model_fields_set:
            _dict['agentContract'] = None

        # set to None if local_id (nullable) is None
        # and model_fields_set contains the field
        if self.local_id is None and "local_id" in self.model_fields_set:
            _dict['localId'] = None

        # set to None if context (nullable) is None
        # and model_fields_set contains the field
        if self.context is None and "context" in self.model_fields_set:
            _dict['context'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageUserSend from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agenticWallet": obj.get("agenticWallet"),
            "message": obj.get("message"),
            "agentContract": obj.get("agentContract"),
            "localId": obj.get("localId"),
            "context": MessageUserSendContext.from_dict(obj["context"]) if obj.get("context") is not None else None
        })
        return _obj


