from enum import Enum

GAMES_URL = "https://umpscorecards.com/api/games/?&season_type={season_type}&start_date={start_date}&end_date={end_date}&team1={home_team}-h&team2={away_team}-a&umpire={umpire_name}&_=1739743220236"
UMPIRES_URL = "https://umpscorecards.com/api/umpires/?&season_type={season_type}&start_date={start_date}&end_date={end_date}&team1={home_team}-h&team2={away_team}-a&_=1739746115431"
TEAMS_URL = "https://umpscorecards.com/api/teams/?&season_type={season_type}&start_date={start_date}&end_date={end_date}&umpire={umpire_name}&team={team}&ha={home_away}&venue={stadium}&_=1739746372270"


class UmpireScorecardTeams(Enum):
    ALL = "*"
    ARI = "ARI"
    ATL = "ATL"
    BAL = "BAL"
    BOS = "BOS"
    CHC = "CHC"
    CIN = "CIN"
    CLE = "CLE"
    COL = "COL"
    CWS = "CWS"
    DET = "DET"
    HOU = "HOU"
    KC = "KC"
    LAA = "LAA"
    LAD = "LAD"
    MIA = "MIA"
    MIL = "MIL"
    MIN = "MIN"
    NYM = "NYM"
    NYY = "NYY"
    OAK = "OAK"
    PHI = "PHI"
    PIT = "PIT"
    SD = "SD"
    SEA = "SEA"
    SF = "SF"
    STL = "STL"
    TB = "TB"
    TEX = "TEX"
    TOR = "TOR"
    WSH = "WSH"
