class UnknownLocationException(Exception):
    def __init__(self, *args: object) -> None: ...

class InvalidStatusCodeException(Exception):
    def __init__(self, *args: object) -> None: ...

class InvalidCollectionException(Exception):
    def __init__(self, *args: object) -> None: ...
