
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-19T17:48:08-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "309a9a270133f489c1e56014aee52da00be7f4bf",
 "version": "2.57.1b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
