
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-21T10:41:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "37d6e42295c2447fec20e402bf2a0210b5992a6d",
 "version": "1.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
