from .samplers import DenoisingDiffusionProbabilisticModelsSampler, DenoisingDiffusionImplicitModelsSampler


DDPMSampler = DenoisingDiffusionProbabilisticModelsSampler
DDIMSampler = DenoisingDiffusionImplicitModelsSampler