from .samplers import DenoisingDiffusionProbabilisticModelsSampler, DenoisingDiffusionImplicitModelsSampler


class DDPMSampler(DenoisingDiffusionProbabilisticModelsSampler): ...
class DDIMSampler(DenoisingDiffusionImplicitModelsSampler): ...