"""
Copyright (c) 2025 ayeteadoe <ayeteadoe@gmail.com>

SPDX-License-Identifier: MIT
"""
from contextlib import contextmanager
from typing import Optional, List, Any
from typeflags import TypeFlags


@contextmanager
def object_created_callback(on_object_created: callable): ...


class Object:
    properties: dict[str, Any]

    def __init__(self, name: str) -> None: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, value: str) -> None: ...

    @property
    def type_flags(self) -> TypeFlags: ...

    @type_flags.setter
    def type_flags(self, value: TypeFlags) -> None: ...

    @property
    def dependencies(self) -> List[str]: ...

    @dependencies.setter
    def dependencies(self, value: List[str]) -> None: ...

    @property
    def hex_colour(self) -> Optional[str]: ...

    @hex_colour.setter
    def hex_colour(self, value: Optional[str]) -> None: ...

    @property
    def shape_type(self) -> str: ...

    @shape_type.setter
    def shape_type(self, value: str) -> None: ...

    def rectangle(self) -> None: ...

    def circle(self) -> None: ...

    def diamond(self) -> None: ...

    def ellipse(self) -> None: ...

    # Read-only type flag properties
    @property
    def is_project(self) -> bool: ...

    @property
    def is_subdirs(self) -> bool: ...

    @property
    def is_target(self) -> bool: ...

    @property
    def is_test(self) -> bool: ...

    @property
    def is_app(self) -> bool: ...

    @property
    def is_lib(self) -> bool: ...

    @property
    def is_header(self) -> bool: ...

    @property
    def is_static(self) -> bool: ...

    @property
    def is_shared(self) -> bool: ...

    @property
    def is_third_party(self) -> bool: ...

    @property
    def is_pkgconfig(self) -> bool: ...

    @property
    def is_precompiled_archive(self) -> bool: ...

    @property
    def is_source_archive(self) -> bool: ...

    @property
    def is_git(self) -> bool: ...

    @property
    def is_vcpkg(self) -> bool: ...

    @property
    def is_conan(self) -> bool: ...

    @property
    def is_apt(self) -> bool: ...

    @property
    def is_dnf(self) -> bool: ...

    @property
    def is_container(self) -> bool: ...

    @property
    def is_static_crt(self) -> bool: ...

    @property
    def is_dynamic_crt(self) -> bool: ...

    @property
    def is_cxx(self) -> bool: ...

    @property
    def is_rust(self) -> bool: ...

    @property
    def is_qt(self) -> bool: ...

    @property
    def is_pybind11(self) -> bool: ...

    @property
    def is_icu(self) -> bool: ...
