# Generated by Django 4.2.16 on 2024-09-12 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_nitro_mailer", "0002_alter_email_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
